service: pifinder
app: pidistributed
org: trozler

frameworkVersion: "2"
plugins:

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"
# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  calculate:
    handler: ./src/app.handler
    events:
      - httpApi:
          path: /calculate
          method: post
    environment:
      workerLamda:
        Ref: WorkerLambdaFunction

  worker:
    handler: ./src/worker.handler
    events:
      - httpApi:
          path: /worker
          method: post
